// Code generated by protoc-gen-go.
// source: gossip.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	gossip.proto

It has these top-level messages:
	Update
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Update messages can be of various types.
type Update_UpdateType int32

const (
	Update_DATA Update_UpdateType = 0
	Update_JOIN Update_UpdateType = 1
)

var Update_UpdateType_name = map[int32]string{
	0: "DATA",
	1: "JOIN",
}
var Update_UpdateType_value = map[string]int32{
	"DATA": 0,
	"JOIN": 1,
}

func (x Update_UpdateType) String() string {
	return proto.EnumName(Update_UpdateType_name, int32(x))
}
func (Update_UpdateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Update struct {
	// the protobuf payload, doesn't matter for the protocol.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// The type of message being sent.
	Type Update_UpdateType `protobuf:"varint,2,opt,name=type,enum=pb.Update_UpdateType" json:"type,omitempty"`
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Update) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Update) GetType() Update_UpdateType {
	if m != nil {
		return m.Type
	}
	return Update_DATA
}

func init() {
	proto.RegisterType((*Update)(nil), "pb.Update")
	proto.RegisterEnum("pb.Update_UpdateType", Update_UpdateType_name, Update_UpdateType_value)
}

func init() { proto.RegisterFile("gossip.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0x2f, 0x2e,
	0xce, 0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xca, 0xe7, 0x62,
	0x0b, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x15, 0x92, 0xe0, 0x62, 0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x85, 0x34, 0xb9, 0x58, 0x4a, 0x2a,
	0x0b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0x44, 0xf5, 0x0a, 0x92, 0xf4, 0x20, 0x7a,
	0xa0, 0x54, 0x48, 0x65, 0x41, 0x6a, 0x10, 0x58, 0x89, 0x92, 0x02, 0x17, 0x17, 0x42, 0x4c, 0x88,
	0x83, 0x8b, 0xc5, 0xc5, 0x31, 0xc4, 0x51, 0x80, 0x01, 0xc4, 0xf2, 0xf2, 0xf7, 0xf4, 0x13, 0x60,
	0x4c, 0x62, 0x03, 0xdb, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x95, 0xf1, 0x88, 0x9a, 0x8b,
	0x00, 0x00, 0x00,
}
